# Generated by Django 4.2.4 on 2023-08-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mati', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
    ]
