# Generated by Django 4.2.4 on 2023-08-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mati', '0003_rename_camada_curso_comision'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
    ]
